### Universal Functions:
#### "A universal function (ufunc), is a function that performs fast element wise operations on the ndarrays. These are the fast vectorized wrappers for simple functions that can take one or more scalar values and produce one or more scalar results."

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Function-1
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
# Function-2
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
# Function-3
# Finding Maximum Array
x = np.random.randn(8)
y = np.random.randn(8)

In [6]:
x

array([ 0.30971878,  0.24451185, -0.66985915,  0.86618966,  0.51919997,
       -1.62464967,  1.45540066, -0.24746477])

In [7]:
y

array([-0.87204037,  0.65905164, -0.1042145 ,  1.95810779,  0.74902387,
       -0.3313756 ,  1.19972042,  0.64543462])

In [9]:
np.maximum(x,y,axis=0)

TypeError: 'axis' is an invalid keyword to ufunc 'maximum'