In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing of an Array

In [3]:
# This is the basic slicing of one element
arr[5]

6

In [4]:
arr[5:8]

array([6, 7, 8])

In [5]:
arr_slice = arr[5:8]
arr_slice

array([6, 7, 8])

- Numpy doesn't creates a copy of an array for slicing. It performs it on the entire existing array.

In [6]:
# Changing the accessed elements
arr_slice[1] = '123'

In [7]:
arr_slice

array([  6, 123,   8])

In [8]:
arr

array([  1,   2,   3,   4,   5,   6, 123,   8,   9,  10])

- Original array changed.

In [9]:
arr_slice

array([  6, 123,   8])

#### Doing Bare Slice

In [10]:
arr_slice[:] = 64

- Bare Slicing will change all the accessed values.

In [11]:
arr

array([ 1,  2,  3,  4,  5, 64, 64, 64,  9, 10])

### Doing slicing on 2d Arrays

In [12]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# Checking Dimensions
arr2d.ndim

2

In [14]:
arr2d[2]

array([7, 8, 9])

In [15]:
# Accessing the first element
arr2d[0][0]

1

In [16]:
# Accessing the last element
arr2d[2][2]

9

### Doing slicing on 3d Arrays

In [17]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
# Checking Dimensions
arr3d.ndim

3

In [19]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# Making the copy of the array
previous_values = arr3d[0].copy()
previous_values

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
arr3d[0] = previous_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
# Accessing the second value of the first array
arr3d[0][0][1]

2

In [24]:
# Accessing the multiple values from an array
arr3d[1,0]

array([7, 8, 9])

In [25]:
arr3d[1,1]

array([10, 11, 12])

In [26]:
x = arr3d[1]
print(x[1])
print(x[1,2])

[10 11 12]
12


In [27]:
x[0]

array([7, 8, 9])

In [28]:
x[0][2]

9

### Indexing With Slicing

In [29]:
arr

array([ 1,  2,  3,  4,  5, 64, 64, 64,  9, 10])

In [30]:
arr[1:6]

array([ 2,  3,  4,  5, 64])

In [31]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### By Slicing like this we obtain the array of the same dimension.

In [32]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

#### By mixing the integers and slices we always get a lower dimension array

In [34]:
arr2d[1,:2] 
# Second row and its first two columns

array([4, 5])

In [35]:
arr2d[:2,1]
# First two rows and their second column

array([2, 5])

In [36]:
arr2d[:2,2]
# First two rows and their third column

array([3, 6])

### Note: [:] means that select an entire axis.So, you can only slice higher dimension axes by using this method.

In [37]:
arr2d[:,:1] 

array([[1],
       [4],
       [7]])

#### Assigning to a slice expression

In [38]:
arr2d[:2,1:] = 0

In [39]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [40]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
# Generating the random normally distributed data
data = np.random.randn(7,4)
print(names)
print("\n")
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


[[-0.07445798  0.22818013 -1.16518392  0.46312541]
 [-1.12480275  0.77702631 -1.97445691  0.69111989]
 [ 0.53298639  0.32437756 -1.65072999  0.21588646]
 [ 0.1698166   1.38140366  1.02504543 -0.29034014]
 [-0.23180186 -0.14431718  0.85109433  1.0393346 ]
 [ 0.14748447  0.54633145  2.25304176  0.47073349]
 [-0.08226633  0.68611973  1.35071627  0.76495912]]


- Suppose that each name represents a row in the data.
- We want to select all the rows corresponding to the name "Bob".
- Compairing the array with the string "Bob" results a boolean array.

In [41]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [42]:
# Extracting the rows where the condition (names == "Bob") satisfies
data[names == "Bob"]

array([[-0.07445798,  0.22818013, -1.16518392,  0.46312541],
       [ 0.1698166 ,  1.38140366,  1.02504543, -0.29034014]])

#### Note: Boolean selection will not fail if the boolean array have incorrect length, So be careful while using it.

In [43]:
# Indexing the coloumns 2 of the rows where (name == "Bob") condition satisfies
data[names == "Bob", 2:]

array([[-1.16518392,  0.46312541],
       [ 1.02504543, -0.29034014]])

In [44]:
data[names == 'Bob', 3]

array([ 0.46312541, -0.29034014])

In [45]:
# To select all except "Bob" we can use negation (~) or not eqaul to (!=) 
# Method-1
data[~(names == 'Bob')]

array([[-1.12480275,  0.77702631, -1.97445691,  0.69111989],
       [ 0.53298639,  0.32437756, -1.65072999,  0.21588646],
       [-0.23180186, -0.14431718,  0.85109433,  1.0393346 ],
       [ 0.14748447,  0.54633145,  2.25304176,  0.47073349],
       [-0.08226633,  0.68611973,  1.35071627,  0.76495912]])

In [46]:
# Method-2
data[names != 'Bob']

array([[-1.12480275,  0.77702631, -1.97445691,  0.69111989],
       [ 0.53298639,  0.32437756, -1.65072999,  0.21588646],
       [-0.23180186, -0.14431718,  0.85109433,  1.0393346 ],
       [ 0.14748447,  0.54633145,  2.25304176,  0.47073349],
       [-0.08226633,  0.68611973,  1.35071627,  0.76495912]])

In [47]:
# Method-3
condition = names == "Bob"
data[~(condition)]

array([[-1.12480275,  0.77702631, -1.97445691,  0.69111989],
       [ 0.53298639,  0.32437756, -1.65072999,  0.21588646],
       [-0.23180186, -0.14431718,  0.85109433,  1.0393346 ],
       [ 0.14748447,  0.54633145,  2.25304176,  0.47073349],
       [-0.08226633,  0.68611973,  1.35071627,  0.76495912]])

#### Method-1, Method-2 and Method-3 shows the same output.

In [48]:
# Alternate way
data[~condition]

array([[-1.12480275,  0.77702631, -1.97445691,  0.69111989],
       [ 0.53298639,  0.32437756, -1.65072999,  0.21588646],
       [-0.23180186, -0.14431718,  0.85109433,  1.0393346 ],
       [ 0.14748447,  0.54633145,  2.25304176,  0.47073349],
       [-0.08226633,  0.68611973,  1.35071627,  0.76495912]])

In [49]:
data

array([[-0.07445798,  0.22818013, -1.16518392,  0.46312541],
       [-1.12480275,  0.77702631, -1.97445691,  0.69111989],
       [ 0.53298639,  0.32437756, -1.65072999,  0.21588646],
       [ 0.1698166 ,  1.38140366,  1.02504543, -0.29034014],
       [-0.23180186, -0.14431718,  0.85109433,  1.0393346 ],
       [ 0.14748447,  0.54633145,  2.25304176,  0.47073349],
       [-0.08226633,  0.68611973,  1.35071627,  0.76495912]])

In [50]:
# Selecting two or three names to combine multiple boolean conditions
# Making a mask
mask = (names == 'Bob') | (names == 'Will')
mask
# In nd array (and) and (or) do not work ,So use (&) for 'and' and (|) for 'or'

array([ True, False,  True,  True,  True, False, False])

In [51]:
data[mask]

array([[-0.07445798,  0.22818013, -1.16518392,  0.46312541],
       [ 0.53298639,  0.32437756, -1.65072999,  0.21588646],
       [ 0.1698166 ,  1.38140366,  1.02504543, -0.29034014],
       [-0.23180186, -0.14431718,  0.85109433,  1.0393346 ]])

#### Overwriting a slice

In [52]:
data[data < 0] = 0
data
# Where there is a negative value replace it with the '0'

array([[0.        , 0.22818013, 0.        , 0.46312541],
       [0.        , 0.77702631, 0.        , 0.69111989],
       [0.53298639, 0.32437756, 0.        , 0.21588646],
       [0.1698166 , 1.38140366, 1.02504543, 0.        ],
       [0.        , 0.        , 0.85109433, 1.0393346 ],
       [0.14748447, 0.54633145, 2.25304176, 0.47073349],
       [0.        , 0.68611973, 1.35071627, 0.76495912]])

#### Replacing a whole row or column

In [53]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.77702631, 0.        , 0.69111989],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.14748447, 0.54633145, 2.25304176, 0.47073349],
       [0.        , 0.68611973, 1.35071627, 0.76495912]])

### Fancy Indexing

In [54]:
arr = np.empty((8,4))
arr

array([[6.79038653e-313, 2.10077583e-312, 2.14321575e-312,
        2.44029516e-312],
       [2.33419537e-312, 6.79038654e-313, 2.20687562e-312,
        6.79038654e-313],
       [2.14321575e-312, 2.35541533e-312, 2.12199579e-312,
        2.50395503e-312],
       [2.29175545e-312, 2.14321575e-312, 2.35541533e-312,
        6.79038654e-313],
       [2.20687562e-312, 6.79038654e-313, 2.22809558e-312,
        2.44029516e-312],
       [6.79038654e-313, 2.41907520e-312, 2.05833592e-312,
        2.12199580e-313],
       [2.41907520e-312, 1.08221785e-312, 1.93101617e-312,
        1.97345609e-312],
       [1.01855798e-312, 1.93101617e-312, 1.97345609e-312,
        0.00000000e+000]])

In [55]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [56]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [57]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

arr = np.arange(32).reshape((8,4))
arr

In [58]:
arr[[1,5,7,2],[0,3,1,2]]

array([1., 5., 7., 2.])

- The result of fancy indexing is always one dimension

In [59]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

- Fancy indexing always copies the data into a new array

### Transposing and Swapping Axis

In [60]:
arr1 = np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
# Taking the transpose of the array
arr1.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [62]:
# Computing the inner matrix product with np.dot()
np.dot(arr.T,arr)

array([[140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.]])

In [63]:
# For higher dimension of arrays transpose is provided in a tuple
arr2 = np.arange(16).reshape(2,2,4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [64]:
arr2.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

- Here the axes have been reordered with the second axis first, the first axis second, and the last axis remained unchaged.

In [65]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
arr2.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

- Swapaxes doesn't make the copy.