In [1]:
import numpy as np

In [2]:
arr = np.arange(10) * 100
inds = [7,1,2,6]

In [3]:
arr[inds]

array([700, 100, 200, 600])

In [5]:
arr.take(inds)

array([700, 100, 200, 600])

In [6]:
arr.put(inds,42)

In [7]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])