In [1]:
import numpy as np

In [2]:
arr = np.arange(10) * 100
# Create an array of 10 elements
inds = [7,1,2,6]

In [3]:
arr[inds]

array([700, 100, 200, 600])

In [5]:
arr.take(inds)

array([700, 100, 200, 600])

In [6]:
arr.put(inds,42)

In [7]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [8]:
inds = [2,0,2,1]
arr1 = np.random.randn(2,4)
arr1

array([[ 1.41129204,  0.338093  , -0.37573245,  1.55003292],
       [ 0.23938843,  0.33997119,  0.85400188,  0.47194634]])

In [9]:
arr1.take(inds, axis=1)

array([[-0.37573245,  1.41129204, -0.37573245,  0.338093  ],
       [ 0.85400188,  0.23938843,  0.85400188,  0.33997119]])

In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
