### Universal Functions:
#### "A universal function (ufunc), is a function that performs fast element wise operations on the ndarrays. These are the fast vectorized wrappers for simple functions that can take one or more scalar values and produce one or more scalar results."

In [34]:
import numpy as np

In [35]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [38]:
x = np.random.randn(8)
y = np.random.randn(8)

In [39]:
x

array([ 0.55375308,  0.50814476,  0.58723139, -1.12103005,  0.42465383,
        0.03422287, -0.09190284, -0.7901171 ])

In [40]:
y

array([-0.34354164, -0.34655887, -0.65570755, -0.53059739, -0.83999158,
       -0.61262624, -0.20595048,  1.14897102])

In [41]:
np.maximum(x,y)

array([ 0.55375308,  0.50814476,  0.58723139, -0.53059739,  0.42465383,
        0.03422287, -0.09190284,  1.14897102])

#### A ufunc can return multiple arrays, below is an example.

In [42]:
arr1 = np.random.randn(7) * 5
arr1

array([-6.2118993 , -2.34724556,  8.28230525,  3.54844976, -1.89227916,
       -1.88692906,  5.58228587])

In [43]:
remainder, whole_part = np.modf(arr1)

In [44]:
remainder

array([-0.2118993 , -0.34724556,  0.28230525,  0.54844976, -0.89227916,
       -0.88692906,  0.58228587])

In [45]:
whole_part

array([-6., -2.,  8.,  3., -1., -1.,  5.])

#### Ufunc accepts an optional argument too.

In [46]:
arr1

array([-6.2118993 , -2.34724556,  8.28230525,  3.54844976, -1.89227916,
       -1.88692906,  5.58228587])

In [53]:
np.sqrt(arr1)

array([       nan,        nan, 1.30247352, 1.17153383,        nan,
              nan, 1.23979965])

In [52]:
np.sqrt(arr1,arr1)

array([       nan,        nan, 1.69643728, 1.37249151,        nan,
              nan, 1.53710317])

In [123]:
np.abs(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [70]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [71]:
np.log(arr)

<ipython-input-71-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [72]:
np.log10(arr)

<ipython-input-72-4473232fb1a0>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [73]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [74]:
np.ceil(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [75]:
np.floor(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [76]:
np.rint(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [77]:
np.isnan(arr)

array([False, False, False, False, False, False, False, False, False,
       False])

In [78]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [79]:
np.isinf(arr)

array([False, False, False, False, False, False, False, False, False,
       False])

In [80]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [81]:
np.cosh(arr)

array([1.00000000e+00, 1.54308063e+00, 3.76219569e+00, 1.00676620e+01,
       2.73082328e+01, 7.42099485e+01, 2.01715636e+02, 5.48317035e+02,
       1.49047916e+03, 4.05154203e+03])

In [82]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [83]:
np.sinh(arr)

array([0.00000000e+00, 1.17520119e+00, 3.62686041e+00, 1.00178749e+01,
       2.72899172e+01, 7.42032106e+01, 2.01713157e+02, 5.48316123e+02,
       1.49047883e+03, 4.05154190e+03])

In [84]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [85]:
np.tanh(arr)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997])

In [87]:
np.arcsin(arr)

<ipython-input-87-5bd4fd3f10d9>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(arr)


array([0.        , 1.57079633,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan])

In [88]:
np.arccos(arr)

<ipython-input-88-5d398094bea0>:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(arr)


array([1.57079633, 0.        ,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan])

In [89]:
np.arcsinh(arr)

array([0.        , 0.88137359, 1.44363548, 1.81844646, 2.09471255,
       2.31243834, 2.49177985, 2.64412076, 2.77647228, 2.89344399])

In [90]:
np.arccosh(arr)

<ipython-input-90-9ee5d7d8183c>:1: RuntimeWarning: invalid value encountered in arccosh
  np.arccosh(arr)


array([       nan, 0.        , 1.3169579 , 1.76274717, 2.06343707,
       2.29243167, 2.47788873, 2.63391579, 2.76865938, 2.88727095])

In [91]:
np.arctan(arr)

array([0.        , 0.78539816, 1.10714872, 1.24904577, 1.32581766,
       1.37340077, 1.40564765, 1.42889927, 1.44644133, 1.46013911])

In [92]:
np.arctanh(arr)

<ipython-input-92-8cdc3947424c>:1: RuntimeWarning: divide by zero encountered in arctanh
  np.arctanh(arr)
<ipython-input-92-8cdc3947424c>:1: RuntimeWarning: invalid value encountered in arctanh
  np.arctanh(arr)


array([ 0., inf, nan, nan, nan, nan, nan, nan, nan, nan])

In [93]:
np.logical_not(arr)

array([ True, False, False, False, False, False, False, False, False,
       False])

### Binary Universal Functions

In [95]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.add(arr,arr1)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [97]:
np.subtract(arr,arr1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
np.multiply(arr,arr1)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [99]:
np.divide(arr,arr1)

<ipython-input-99-c7d5961ae8fa>:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(arr,arr1)


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [100]:
np.floor_divide(arr,arr1)

<ipython-input-100-7e94104a3f0b>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.floor_divide(arr,arr1)


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [101]:
np.power(arr,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [102]:
np.power(arr,arr1)

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [103]:
np.maximum(arr,arr1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.fmax(arr,arr1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.minimum(arr,arr1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.fmin(arr,arr1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.mod(arr,arr1)

<ipython-input-109-c9e419ea39ef>:1: RuntimeWarning: divide by zero encountered in remainder
  np.mod(arr,arr1)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [110]:
np.copysign(arr,arr1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [111]:
np.greater(arr,arr1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [112]:
np.greater_equal(arr,arr1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [115]:
np.less(arr,arr1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [116]:
np.less_equal(arr,arr1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [117]:
np.equal(arr,arr1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [118]:
np.not_equal(arr,arr1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [120]:
np.logical_and(arr,arr1)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [121]:
np.logical_or(arr,arr1)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [122]:
np.logical_xor(arr,arr1)

array([False, False, False, False, False, False, False, False, False,
       False])