In [1]:
import numpy as np

In [2]:
arr = np.arange(10) * 100
# Create an array of 10 elements
inds = [7,1,2,6]

In [3]:
arr[inds]

array([700, 100, 200, 600])

In [5]:
arr.take(inds)

array([700, 100, 200, 600])

In [6]:
arr.put(inds,42)

In [7]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [24]:
inds = [2,0,2,1]
arr1 = np.random.randn(2,4)
arr1

array([[-1.24683479,  0.9655418 ,  1.01361746,  0.86405832],
       [-0.0372522 , -1.17797389,  0.2188432 , -0.64490526]])

In [25]:
arr1.take(inds, axis=1)

array([[ 1.01361746, -1.24683479,  1.01361746,  0.9655418 ],
       [ 0.2188432 , -0.0372522 ,  0.2188432 , -1.17797389]])

In [26]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
index = [0,1,2,3,4,5,6,7,8,9]
arr2[index]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr2.take(index)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr2.put(index,[2,4,65,98,100,34,22,38,55,20])

In [29]:
arr2

array([  2,   4,  65,  98, 100,  34,  22,  38,  55,  20])

In [30]:
arr1

array([[-1.24683479,  0.9655418 ,  1.01361746,  0.86405832],
       [-0.0372522 , -1.17797389,  0.2188432 , -0.64490526]])

In [31]:
arr1.put(1,5)

In [32]:
arr1

array([[-1.24683479,  5.        ,  1.01361746,  0.86405832],
       [-0.0372522 , -1.17797389,  0.2188432 , -0.64490526]])