In [7]:
import numpy as np

### Array Oriented Programming

#### Np.repeat() and Np.tile() mthod

In [8]:
arr = np.arange(15)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr.repeat(3)
# Repeating each element for a particular number of times in an array

array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
        5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
       11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14])

In [11]:
arr.reshape(5,3).repeat(2,axis=0)
# Repeating in multidimensional array

array([[ 0,  1,  2],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 9, 10, 11],
       [12, 13, 14],
       [12, 13, 14]])

#### Expressing Conditional Logic As Array Operations

In [12]:
# np.where() serves the purpose of conditional work in the Numpy

In [13]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

In [14]:
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])