In [2]:
import numpy as np

### Transposing and Swapping Axis

In [3]:
arr1 = np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
arr = np.random.randn(6,3)
arr

array([[-0.59698856, -1.62298091,  0.47135829],
       [-2.93766586, -0.12584466,  0.94845985],
       [-0.41796422,  2.24582483,  1.01776566],
       [ 0.12221875, -1.36896957, -0.59254706],
       [-0.76445385, -3.04701603, -0.5206847 ],
       [ 0.29113447,  0.44221276,  0.51642975]])

In [11]:
# Taking the transpose of the array
arr1.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [12]:
# Computing the inner matrix product with np.dot()
np.dot(arr.T,arr)

array([[ 9.84505655,  2.69064894, -3.01707368],
       [ 2.69064894, 19.04756958,  4.02744464],
       [-3.01707368,  4.02744464,  3.04652591]])

In [13]:
# For higher dimension of arrays transpose is provided in a tuple
arr2 = np.arange(16).reshape(2,2,4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
arr2.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [16]:
# Here the axes have been reordered with the second axis first, the first axis second, and the last axis remained unchaged.
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
arr2.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

- Swapaxes doesn't make the copy.
