In [2]:
import numpy as np

### Array Oriented Programming

#### Np.repeat() and Np.tile() mthod

In [3]:
arr = np.arange(15)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr.repeat(3)
# Repeating each element for a particular number of times in an array

array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
        5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
       11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14])

In [8]:
arr.reshape(5,3).repeat(2,axis=0)
Rep

array([[ 0,  1,  2],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 9, 10, 11],
       [12, 13, 14],
       [12, 13, 14]])