In [1]:
import numpy as np

### Repeat Function 

In [2]:
arr = np.array([0,1,2,3,4,5])

In [8]:
np.repeat(arr, 2)
# Repeating each element for the 2 times

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [10]:
np.repeat(arr, 5)
# Repeating each element for the 5 times

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5])

In [11]:
arr2d = np.arange(20).reshape(5,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
np.repeat(arr2d,3,axis=0)

array([[ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [12, 13, 14, 15],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [16, 17, 18, 19],
       [16, 17, 18, 19]])

In [13]:
np.repeat(arr2d,3,axis=1)

array([[ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3],
       [ 4,  4,  4,  5,  5,  5,  6,  6,  6,  7,  7,  7],
       [ 8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11],
       [12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15],
       [16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19]])

#### Repeating a particular value to a particular number of times

In [14]:
arr

array([0, 1, 2, 3, 4, 5])

In [19]:
arr.repeat([2,3,1,1,1,1],axis=0)

array([0, 0, 1, 1, 1, 2, 3, 4, 5])

In [20]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
np.tile(arr2d,(2,1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])