In [1]:
import numpy as np

In [37]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing of an Array

In [36]:
# This is the basic slicing of one element
arr[5]

5

In [4]:
arr[5:8]

array([6, 7, 8])

In [5]:
arr_slice = arr[5:8]
arr_slice

array([6, 7, 8])

- Numpy doesn't creates a copy of an array for slicing. It performs it on the entire existing array.

In [6]:
# Changing the accessed elements
arr_slice[1] = '123'

In [7]:
arr_slice

array([  6, 123,   8])

In [8]:
arr

array([  1,   2,   3,   4,   5,   6, 123,   8,   9,  10])

- Original array changed.

In [9]:
arr_slice

array([  6, 123,   8])

#### Doing Bare Slice

In [10]:
arr_slice[:] = 64

- Bare Slicing will change all the accessed values.

In [11]:
arr

array([ 1,  2,  3,  4,  5, 64, 64, 64,  9, 10])

### Doing slicing on 2d Arrays

In [54]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# Checking Dimensions
arr2d.ndim

2

In [14]:
arr2d[2]

array([7, 8, 9])

In [15]:
# Accessing the first element
arr2d[0][0]

1

In [16]:
# Accessing the last element
arr2d[2][2]

9

### Doing slicing on 3d Arrays

In [17]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
# Checking Dimensions
arr3d.ndim

3

In [19]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# Making the copy of the array
previous_values = arr3d[0].copy()
previous_values

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
arr3d[0] = previous_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
# Accessing the second value of the first array
arr3d[0][0][1]

2

In [24]:
# Accessing the multiple values from an array
arr3d[1,0]

array([7, 8, 9])

In [25]:
arr3d[1,1]

array([10, 11, 12])

In [26]:
x = arr3d[1]
print(x[1])
print(x[1,2])

[10 11 12]
12


In [27]:
x[0]

array([7, 8, 9])

In [28]:
x[0][2]

9

### Indexing With Slicing

In [29]:
arr

array([ 1,  2,  3,  4,  5, 64, 64, 64,  9, 10])

In [30]:
arr[1:6]

array([ 2,  3,  4,  5, 64])

In [31]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### By Slicing like this we obtain the array of the same dimension.

In [32]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

#### By mixing the integers and slices we always get a lower dimension array

In [38]:
arr2d[1,:2] 
# Second row and its first two columns

array([4, 5])

In [40]:
arr2d[:2,1]
# First two rows and their second column

array([2, 5])

In [42]:
arr2d[:2,2]
# First two rows and their third column

array([3, 6])

### Note: [:] means that select an entire axis.So, you can only slice higher dimension axes by using this method.

In [43]:
arr2d[:,:1] 

array([[1],
       [4],
       [7]])

#### Assigning to a slice expression

In [56]:
arr2d[:2,1:] = 0

In [57]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [61]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
# Generating the random normally distributed data
data = np.random.randn(7,4)
print(names)
print("\n")
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


[[ 0.21688874 -0.32944966  0.4763424   0.75914947]
 [-0.82110658  0.81878692 -0.91243927  1.40678805]
 [ 0.44848908 -0.54764545 -0.81949276  0.28045021]
 [ 0.70327991 -1.09201579 -0.18802087  0.53769415]
 [ 2.15977348 -0.00923796 -1.89751787  1.08048096]
 [ 0.6303987  -1.01828508 -0.9633642   0.28976953]
 [-0.05303229 -0.24100821  0.70067928 -0.60997615]]


- Suppose that each name represents a row in the data.
- We want to select all the rows corresponding to the name "Bob".
- Compairing the array with the string "Bob" results a boolean array.

In [62]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [63]:
# Extracting the rows where the condition (names == "Bob") satisfies
data[names == "Bob"]

array([[ 0.21688874, -0.32944966,  0.4763424 ,  0.75914947],
       [ 0.70327991, -1.09201579, -0.18802087,  0.53769415]])

#### Note: Boolean selection will not fail if the boolean array have incorrect length, So be careful while using it.

In [68]:
# Indexing the coloumns 2 of the rows where (name == "Bob") condition satisfies
data[names == "Bob", 2:]

array([[ 0.4763424 ,  0.75914947],
       [-0.18802087,  0.53769415]])

In [69]:
data[names == 'Bob', 3]

array([0.75914947, 0.53769415])

In [70]:
# To select all except "Bob" we can use negation (~) or not eqaul to (!=) 
# Method-1
data[~(names == 'Bob')]

array([[-0.82110658,  0.81878692, -0.91243927,  1.40678805],
       [ 0.44848908, -0.54764545, -0.81949276,  0.28045021],
       [ 2.15977348, -0.00923796, -1.89751787,  1.08048096],
       [ 0.6303987 , -1.01828508, -0.9633642 ,  0.28976953],
       [-0.05303229, -0.24100821,  0.70067928, -0.60997615]])

In [71]:
# Method-2
data[names != 'Bob']

array([[-0.82110658,  0.81878692, -0.91243927,  1.40678805],
       [ 0.44848908, -0.54764545, -0.81949276,  0.28045021],
       [ 2.15977348, -0.00923796, -1.89751787,  1.08048096],
       [ 0.6303987 , -1.01828508, -0.9633642 ,  0.28976953],
       [-0.05303229, -0.24100821,  0.70067928, -0.60997615]])

In [ ]:
# Method-3
co